### ISSUE TITLE
Merge cubehelix into palettable

### ISSUE THREAD

**Issue by jonathansick** [jiffyclub/palettable#12]
I'm often importing both palettable for the qualitative/divergent maps and [cubehelix](https://github.com/jradavenport/cubehelix) from @jradavenport for continuous maps in my plotting projects. I was wondering: could we merge the cubehelix smarts into palettable?

I think the ideal implementation would be to make a cubehelix sub package containing a `Cubehelix` subclass of `Palettable`.

`Cubehelix.__init__()` would take the same arguments as [`cubehelix.cmap`](https://github.com/jradavenport/cubehelix/blob/master/cubehelix.py#L7-L9) allowing a person to make an arbitrary cubehelix map.

The `cubehelix` sub package would also include several pre-baked cubehelix maps, like the colorbrewer and tableau sub packages already do.

@jiffyclub: would you be interested in a PR for this?

@jradavenport: would it be ok with you (given licensing) to take `cubehelix.cmap` and re-mix it into palettable?

(This is in the same spirit as #8 but I wanted to make a new issue for this specific proposal)

**Comment by jiffyclub** [comment]
I'd definitely be glad to have cubehelix in here if @jradavenport is up for it!

**Comment by jonathansick** [comment]
Great. And I'm not sure I was entirely clear in my message, @jradavenport, but I can do the implementation of the PR. I just wanted your blessing first.

**Comment by jradavenport** [comment]
I'd be thrilled to have cubehelix integrated!! You definitely have my blessing, let me know how I can help!

**Comment by jradavenport** [comment]
Also it would probably help me touch up cubhelix.py to suck less!

**Comment by jonathansick** [comment]
Fixed by #13
