### ISSUE TITLE
Brown sequential colorbrewer

### ISSUE THREAD

**Issue by mike-charles** [jiffyclub/palettable#14]
Would you be able to add a brown sequential colorbrewer scale? It's available in the [diverging color scale](https://jiffyclub.github.io/palettable/colorbrewer/diverging/#brbg_10) but not in the sequential.

The closest I could find is [Yellow/Orange/Brown](https://jiffyclub.github.io/palettable/colorbrewer/sequential/#ylorbr_7) but it's awkward for the low end of precipitation quantities, which should just be brown.

I'd contribute it myself but I'm not sure if you have a quick and/or automated way of producing these colors.

Thanks!

**Comment by jiffyclub** [comment]
The colorbrewer scales all come straight from http://colorbrewer2.org/ and I don't plan to try to imitate anything from there.

You might find something good in http://matplotlib.org/cmocean/, or failing that you can generate your own colormaps using matplotlib's [LinearSegmentedColormap](http://matplotlib.org/api/colors_api.html#matplotlib.colors.LinearSegmentedColormap).

**Comment by mike-charles** [comment]
I apologize, there isn't a brown brewer scale to begin with. I guess I need to learn more about the brewer color scales and where they came from. I'll close this.

Ah, just saw your reply, thanks again.
