### ISSUE TITLE
Addition of perceptually uniform color maps for scientific data

### ISSUE THREAD

**Issue by MarkWieczorek** [jiffyclub/palettable#27]
Would it be possible to add additional perceptually uniform color maps for scientific data? There are several on this web site that are better suited to the geosciences than viridis, inferno and magma:

http://www.fabiocrameri.ch/colourmaps.php

**Comment by Crameri** [comment]
fyi: that would be fine with me. Should you agree that adding them is useful too, the scientific colour-maps are available in a variety of common data formats on my webpage (see above). Let me know, if any other format is preferred though.

**Comment by jiffyclub** [comment]
@Crameri, I'd love to add these, how would you like the module named within `palettable`? `crameri`? `geo`? `scientific`?

**Comment by Crameri** [comment]
„Scientific“ would be fine. Cheers!

**Comment by jiffyclub** [comment]
These are now included in version 3.3.0! https://jiffyclub.github.io/palettable/scientific/

Thanks for the suggestion, and thanks @Crameri for permission to add these.

**Comment by dcherian** [comment]
The preview images aren't showing on that link?

**Comment by jiffyclub** [comment]
@dcherian thanks for letting me know, I believe I've got that fixed!
