### ISSUE TITLE
[Request] A gallery of all the different palettes to choose from on the docs

### ISSUE THREAD

**Issue by jolespin** [jiffyclub/palettable#28]
I want to start experimenting with `palettable` but I don't know where to begin.  Is it possible to have something similar to this on your documentation so users can easily navigate which colormaps they prefer? 

![image](https://user-images.githubusercontent.com/9061708/49532724-07770180-f872-11e8-89cf-b399f52ca8fe.png)

**Comment by jiffyclub** [comment]
Having an abbreviated comparison is a good idea! For now, if you click deeper into the documentation you can find previews of all the palettes, for example at https://jiffyclub.github.io/palettable/mycarta/.

**Comment by jolespin** [comment]
Oh yea those will definitely work.  The cmocean palettes look awesome!  I didn’t see those before.  

Are there any diverging palettes with black in middle and red/green extremes like the classic microarray palettes?

**Comment by jiffyclub** [comment]
Not that I know of, the closest looks like https://jiffyclub.github.io/palettable/cartocolors/diverging/#temps_2

If these microarray palettes are open source they could probably be added to palettable!
