### ISSUE TITLE
Python 3.8 installing from pip

### ISSUE THREAD

**Issue by scottstanie** [jiffyclub/palettable#38]
Hi, is there any reason to not add Python 3.8 to the setup.py version list? As it is, pip doesn't find it when using 3.8 since it only lists up to 3.7

**Comment by jiffyclub** [comment]
No reason, it only hasn't been updated recently. It works in Python 3.8 as far as I know. Are you using a particular pip setting or version? I just tried `pip install snakeviz` with pip 20.2.3 and it installed ok.

**Comment by scottstanie** [comment]
Hmm I I'm also using that version, and unfortunately (or fortunately?) I can't reproduce my error- the install works fine now. Sorry about that!
